#!/bin/sh

# Move an existing config directory to $SNAP_USER_COMMON
# (which is shared across revisions of the snap).
if [ ! -d "$SNAP_USER_COMMON/unvanquished" ]; then
  if [ -d "$SNAP_USER_DATA/.local/share/unvanquished" ]; then
    mv "$SNAP_USER_DATA/.local/share/unvanquished" "$SNAP_USER_COMMON/"
  fi
fi

export XDG_DATA_HOME="${SNAP_USER_COMMON}"
export XDG_CONFIG_HOME="${SNAP_USER_COMMON}"

exec "$SNAP/usr/lib/unvanquished/daemon" "$@"
