name: unvanquished-alpo
base: core24
version: '0.56.2'
adopt-info: metainfo
grade: stable
confinement: strict

icon: snap/gui/unvanquished.png

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  riscv64:
    build-on: [riscv64]
    build-for: [riscv64]

apps:
  unvanquished:
    extensions: [gnome]
    command: usr/bin/unvanquished-launcher.sh $SNAP/usr/lib/unvanquished/daemon
    common-id: net.unvanquished.Unvanquished
    environment:
      XDG_DATA_HOME: $SNAP_USER_COMMON
      XDG_CONFIG_HOME: $SNAP_USER_COMMON
    plugs:
      - network
      - network-bind
      - audio-playback
      - joystick
      - shmem

plugs:
  shmem:
    interface: shared-memory
    private: true

parts:
  metainfo:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/share/metainfo/
      cp $CRAFT_PROJECT_DIR/net.unvanquished.Unvanquished.metainfo.xml $CRAFT_PART_INSTALL/usr/share/metainfo
    parse-info:
      - usr/share/metainfo/net.unvanquished.Unvanquished.metainfo.xml
  
  launcher:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cp $CRAFT_PROJECT_DIR/unvanquished-launcher.sh $CRAFT_PART_INSTALL/usr/bin
      chmod 755 $CRAFT_PART_INSTALL/usr/bin/unvanquished-launcher.sh

  sdl3:
    after: [metainfo, launcher]
    plugin: cmake
    source: https://github.com/libsdl-org/SDL.git
    source-type: git
    source-tag: release-3.4.12
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DSDL_TESTS=OFF
      - -DSDL_X11_XSCRNSAVER=OFF
      - -DSDL_PIPEWIRE=ON
      - -DSDL_PIPEWIRE_SHARED=ON
    build-packages:
      - build-essential
      - ninja-build
      - libpipewire-0.3-dev
      - libwayland-dev
      - libdecor-0-dev
  
  unvanquished:
    after: [metainfo, launcher, sdl3]
    plugin: nil
    source: https://github.com/Unvanquished/Unvanquished.git
    source-type: git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/unvanquished
      
      cd $CRAFT_PART_SRC
      mkdir -p build/pkg
      ./download-paks build/pkg
      cd build
      cmake .. -DUSE_EXTERNAL_DEPS_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
      make -j$(nproc)

      cd $CRAFT_PART_SRC
      cp -r build/* $CRAFT_PART_INSTALL/usr/lib/unvanquished/
    override-prime: |
      craftctl default
      cd $CRAFT_PART_INSTALL/usr/lib/unvanquished/
      patchelf --clear-execstack irt_core-*
    build-environment:
      - PYTHONPATH: /usr/lib/python3/dist-packages:$PYTHONPATH
    build-packages:
      - git
      - build-essential
      - cmake
      - zlib1g-dev
      - libgmp-dev
      - nettle-dev
      - libcurl4-openssl-dev
      - libglew-dev
      - libpng-dev
      - libjpeg-dev
      - libwebp-dev
      - libopenal-dev
      - libogg-dev
      - libvorbis-dev
      - libopus-dev
      - libopusfile-dev
      - libdecor-0-dev
      - liblua5.4-dev
      - patchelf
      - libfreetype-dev
      - libncurses-dev
      - aria2
      - python3
      - python3-yaml
      - python3-jinja2
    stage-packages:
      - zlib1g
      - libgmp10
      - libcurl4t64
      - libpng16-16t64
      - libnettle8t64
      - liblua5.4-0
      - libopenal1
      - libopusfile0
      - libjpeg8
      - libglew2.2
      - libwebp7
      - libopus0
      - libogg0
      - libvorbis0a
      - libdecor-0-0
      - libfreetype6
      - libncurses6
  
  cleanup:
    after:
      - unvanquished
      - metainfo
      - launcher
      - sdl3
    plugin: nil
    build-snaps:
      - core24
      - gnome-46-2404
      - mesa-2404
    override-prime: |
      set -eux
      for snap in "core24" "gnome-46-2404" "mesa-2404"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "$CRAFT_PRIME/{}" \;
      done
  
