name: unvanquished-alpo
base: core26
version: '0.56.2'
adopt-info: metainfo
grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  armhf:
    build-on: [riscv64]
    build-for: [riscv64]

apps:
  unvanquished:
    extensions: [gpu]
    command: usr/bin/unvanquished-launcher.sh $SNAP/usr/lib/unvanquished/daemon
    common-id: net.unvanquished.Unvanquished
    environment:
      XDG_DATA_HOME: $SNAP_USER_COMMON
      XDG_CONFIG_HOME: $SNAP_USER_COMMON
    plugs:
      - network
      - network-bind
      - audio-playback
      - joystick
      - shmem

plugs:
  shmem:
    interface: shared-memory
    private: true

parts:
  metainfo:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/share/metainfo/
      cp $CRAFT_PROJECT_DIR/net.unvanquished.Unvanquished.metainfo.xml $CRAFT_PART_INSTALL/usr/share/metainfo
    parse-info:
      - usr/share/metainfo/net.unvanquished.Unvanquished.metainfo.xml
  
  launcher:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cp $CRAFT_PROJECT_DIR/unvanquished-launcher.sh $CRAFT_PART_INSTALL/usr/bin
      chmod 755 $CRAFT_PART_INSTALL/usr/bin/unvanquished-launcher.sh
  
  unvanquished:
    after: [metainfo, launcher]
    plugin: nil
    source: https://github.com/Unvanquished/Unvanquished.git
    source-type: git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/unvanquished
      
      cd $CRAFT_PART_SRC
      mkdir -p build/pkg
      ./download-paks build/pkg
      cd build
      cmake .. -DUSE_EXTERNAL_DEPS_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
      make -j$(nproc)

      cd $CRAFT_PART_SRC
      cp -r build/* $CRAFT_PART_INSTALL/usr/lib/unvanquished/
    override-prime: |
      craftctl default
      cd $CRAFT_PART_INSTALL/usr/lib/unvanquished/
      patchelf --clear-execstack irt_core-*
    build-packages:
      - git
      - build-essential
      - cmake
      - python3-yaml
      - python3-jinja2
      - zlib1g-dev
      - libgmp-dev
      - nettle-dev
      - libcurl4-openssl-dev
      - libsdl3-dev
      - libglew-dev
      - libpng-dev
      - libjpeg9
      - libwebp7
      - libopenal-dev
      - libogg-dev
      - libvorbis-dev
      - libopus-dev
      - libopusfile-dev
      - libdecor-0-dev
      - liblua5.5-dev
      - patchelf
      - libfreetype-dev
      - libncurses-dev
    stage-packages:
      - zlib1g
      - libgmp10
      - libcurl4t64
      - libpng16-16t64
      - libnettle8t64
      - liblua5.5-0
      - libopenal1
      - libopusfile0
      - libsdl3-0
      - libjpeg9-dev
      - libglew2.2
      - libwebp7
      - libopus0
      - libogg0
      - libvorbis0a
      - libdecor-0-0
      - libfreetype6
      - libncurses6
  
  cleanup:
    after:
      - unvanquished
      - metainfo
      - launcher
    plugin: nil
    build-snaps:
      - core26
      - mesa-2604
    override-prime: |
      set -eux
      for snap in "core26" "mesa-2604"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "$CRAFT_PRIME/{}" \;
      done
  
