name: unvanquished-alpo
base: core24
version: '0.56.2'
adopt-info: metainfo
grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]

apps:
  unvanquished:
    extensions: [gnome]
    command: usr/bin/unvanquished-launcher.sh $SNAP/usr/lib/unvanquished/daemon
    common-id: net.unvanquished.Unvanquished
    environment:
      XDG_DATA_HOME: $SNAP_USER_COMMON
    plugs:
      - network
      - network-bind
      - audio-playback
      - joystick
      - shmem

plugs:
  shmem:
    interface: shared-memory
    private: true

parts:
  metainfo:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/share/metainfo/
      cp $CRAFT_PROJECT_DIR/net.unvanquished.Unvanquished.metainfo.xml $CRAFT_PART_INSTALL/usr/share/metainfo
    parse-info:
      - usr/share/metainfo/net.unvanquished.Unvanquished.metainfo.xml
  
  launcher:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cp $CRAFT_PROJECT_DIR/unvanquished-launcher.sh $CRAFT_PART_INSTALL/usr/bin
  
  unvanquished:
    after: [metainfo, launcher]
    plugin: nil
    source: https://github.com/Unvanquished/Unvanquished/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/unvanquished_${SNAPCRAFT_PROJECT_VERSION}.zip
    source-type: zip
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/unvanquished
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/unvanquished/pkg
      
      cd $CRAFT_PART_SRC
      cd unvanquished_${SNAPCRAFT_PROJECT_VERSION}
      unzip linux-${CRAFT_ARCH_BUILD_FOR}.zip -d $CRAFT_PART_INSTALL/usr/lib/unvanquished
      cp pkg/* $CRAFT_PART_INSTALL/usr/lib/unvanquished/pkg
    override-prime: |
      craftctl default
      cd /usr/lib/unvanquished/
      patchelf --clear-execstack irt_core-*
    build-packages:
      - unzip
      - patchelf
    stage-packages:
      - zlib1g
      - liblua5.3-0
      - libopenal1
      - libopusfile0
  
  gpu-2404:
    after: [unvanquished]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      # Workaround for https://bugs.launchpad.net/snapd/+bug/2055273
      mkdir -p "${CRAFT_PRIME}/gpu-2404"
    prime:
    - bin/gpu-2404-wrapper
